// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTVRxsGo-nNPsYnDTf4nR4iQMfuQuyvZo',
    appId: '1:328394741009:web:3864b2fa64ee0286fda8b0',
    messagingSenderId: '328394741009',
    projectId: 'bruxism-87ee3',
    authDomain: 'bruxism-87ee3.firebaseapp.com',
    storageBucket: 'bruxism-87ee3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaVhIHBqEEMa7mFDOl9KM73U-TMS0mGwU',
    appId: '1:328394741009:android:7625c460d6dbfbf6fda8b0',
    messagingSenderId: '328394741009',
    projectId: 'bruxism-87ee3',
    storageBucket: 'bruxism-87ee3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSV5Fu9qoK6f_EuQhc08VpEGAQ5JgaHmo',
    appId: '1:328394741009:ios:ce9f3bdf3fd48597fda8b0',
    messagingSenderId: '328394741009',
    projectId: 'bruxism-87ee3',
    storageBucket: 'bruxism-87ee3.appspot.com',
    iosClientId: '328394741009-8t76gpnnjset0htnbfoloe9u3fn6a262.apps.googleusercontent.com',
    iosBundleId: 'ai.bruxism.bruxism2',
  );
}
